vich_uploader:
    db_driver: orm

    mappings:
        cat_image:
           uri_prefix: /img/cats
           upload_destination: '%kernel.project_dir%/public/img/cats'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true
           delete_on_update: true
        kitten_image:
           uri_prefix: /img/kittens
           upload_destination: '%kernel.project_dir%/public/img/kittens'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true
           delete_on_update: true


